ratings:
  namespace: student14-bookinfo-dev
  image: ghcr.io/supakkavee/bookinfo-ratings
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student14/ratings(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v1
  ENABLE_EXTERNAL_BOOK_SERVICE: "true"